### ISSUE TITLE
lag compensation for npcs

### ISSUE THREAD

**Issue by ampreeT** [ampreeT/SourceCoop#10]
theres a netprop that every entity that is related to lag comepnsation. we should test whether if adding entities to lag compensation table on entity initialization will work

**Comment by Alienmario** [comment]
Todo - Verify this is actually an issue in BM

**Comment by ampreeT** [comment]
Lag compensation for NPCs is verified to be working by setting client cvar `cl_lagcompensate` or hidden server cvar `sv_unlag_npc` to `0`. On a different note, lag compensation is causing issues with pose parameters being reset (#112).

Closed.
