### ISSUE TITLE
Thirdperson plugin causes sv_cheats state enabled

### ISSUE THREAD

**Issue by yarik2720** [ampreeT/SourceCoop#100]
When plugin `srccoop_addon_thirdperson.smx` is enabled, the cvar state of `sv_cheats` on client became is enabled. 
This causes that anti-cheat plugins like lilac or smac detects wrong cvar on clients

**Comment by Alienmario** [comment]
This is expected, documented and the only way to do proper third-person. It also breaks some weapon animations. It's encouraged to disable the plugin unless you are willing to accept its issues.

PS. Do you really need anticheat plugins on a coop server?

**Comment by yarik2720** [comment]
> Do you really need anticheat plugins on a coop server?

yes, usually to restrict scripted bhop

**Comment by yarik2720** [comment]
> It's encouraged to disable the plugin unless you are willing to accept its issues.

yes, this is why thirdperson is now disabled on server
