### ISSUE TITLE
Flashlight fix

### ISSUE THREAD

**Issue by therepower** [ampreeT/SourceCoop#101]
hello,
the flashlight in coop was horrible and we could not see anything when other players have flashlight on. 
So i digged around and found this command
r_flashlight_3rd_draw 0
which fixes that issue.

You should add this to the Readme

**Comment by Alienmario** [comment]
Automated fix added in https://github.com/ampreeT/SourceCoop/commit/9f7588dde9aed03f65403d09f4b3fa7d2a033035.
