### ISSUE TITLE
Enemies are always aggro even if you try to be stealthy/out of view 

### ISSUE THREAD

**Issue by Venuska1117** [ampreeT/SourceCoop#105]
For some reason, no matter what you do enemies ALWAYS know where you are (on nearly all maps), even if you never made visual contact and try be stealthy, it sometimes lead to absurd situations where enemy will try shoot you trough walls.

https://github.com/ampreeT/SourceCoop/assets/89580971/2ff00586-b34c-4e2b-b03c-f79b4e423071

_(before this video i was attacked same way and died miserable so i tryied to replicate this in video)_

P.S. Better example you can see are turrets, because even if you walk behind them, they will keep trying to shoot you even if you are out of their range of view by standing behind them.

**Comment by ampreeT** [comment]
I tested this with marine NPCs on the map `bm_c1a3b` and found that the NPCs always know where you are on both singleplayer and multiplayer. Though, I have also found that they still remember spotted players after they have died and will seek them out immediately after the player respawns.
