### ISSUE TITLE
Players get stuck on bm_c1a4a elevator.

### ISSUE THREAD

**Issue by Venuska1117** [ampreeT/SourceCoop#107]
If you dont go on ride, you will get stuck here, and for some reason you cant get ladder because door on right is locked/don't react.

![image](https://github.com/ampreeT/SourceCoop/assets/89580971/ad39e60d-e300-410c-82d2-35723f8d9815)

**Comment by Alienmario** [comment]
You should be able to climb back up and go through a vent in a wall (on the right).

**Comment by Venuska1117** [comment]
> You should be able to climb back up and go through a vent in a wall (on the right upper floor).

ah sorry, i didn't know there is vent for this (lack of indicators)
