### ISSUE TITLE
implement player thirdperson animations when not holding any weapon

### ISSUE THREAD

**Issue by ampreeT** [ampreeT/SourceCoop#11]
game defaults the player entity to t-pose when not holding any weapons
- tried 2 options, both failed
  - cannot do serverside animations, client seems to ignore everything even when m_bClientSideAnimation is false
  - unable to recompile player models due to too many animation files overflow in studiomdl

**Comment by Alienmario** [comment]
Having this does not appear probable, since then we have added crowbars to the few first maps. Going to close this for now.
