### ISSUE TITLE
Vehicles reset their pose parameters when damaged

### ISSUE THREAD

**Issue by MyGamepedia** [ampreeT/SourceCoop#112]
Only for tau and bullet weapons, crowbar and explosives doesn't cause this (I have no idea what about gluon gun). Tested with `npc_abrams`, `npc_sentry_ceiling`, `npc_sentry_ground` and `npc_lav`.
Because of this at end of `bm_c3a1b` we can get stuck at moment when the abrams should break the big metal door (this happened to me several times and we had to restart the level). If someone will shoot at the abrams - it will not break the door.
Just a showcase.

https://github.com/ampreeT/SourceCoop/assets/103366204/8a64f776-dee5-4489-b35a-fccb6e2f7cd2

**Comment by Alienmario** [comment]
Ah, that better explains issue https://github.com/ampreeT/SourceCoop/issues/2
Thanks.
