### ISSUE TITLE
`bm_c2a5g` softlock in osprey scene

### ISSUE THREAD

**Issue by MyGamepedia** [ampreeT/SourceCoop#116]
Somehow the scripts broke and did not allow the game to progress further, the only thing I can assume is that presence of large number of players broke the behavior of the vortigaunts, which are should to attack bullseyes in this scene that launch the scripts.
The only reliable solution to the problem that I can suggest is to add output for `logic_relay` that use name `fly_by`. The output is: `OnTrigger ft_relay:Trigger::30:1`.
I was lucky that at this time I was recording this video.

https://github.com/ampreeT/SourceCoop/assets/103366204/ba7dbd33-17ea-4c2f-ad3d-06d834ffa070

**Comment by Alienmario** [comment]
Possibly related to https://github.com/ampreeT/SourceCoop/issues/112

**Comment by MyGamepedia** [comment]
Close this issue for now, if it'll happen again - I will reopen it.
