### ISSUE TITLE
bm_c4a3d - Laser killing in vent

### ISSUE THREAD

**Issue by MCone4SV** [ampreeT/SourceCoop#126]
When you enter the vent before the glass area if you start to go back right after you got sucked in - you'll be killed by the lasers which are behind this vent
https://www.youtube.com/watch?v=pZ4SkoFbd_o

**Comment by Alienmario** [comment]
This is actually an issue in base game.

**Comment by Alienmario** [comment]
https://github.com/ampreeT/SourceCoop/commit/e82e58d35070b26255bd8c089bef08c1b51e96cc
