### ISSUE TITLE
Killfeed not working

### ISSUE THREAD

**Issue by gysiguy** [ampreeT/SourceCoop#149]
I installed the mod on a Black Mesa dedicated server and everything is working except for the killfeed. The only thing that shows up is "Suicide" whenever a player dies, even if they were killed by NPCs. Nothing shows up when players get kills.

**Comment by ampreeT** [comment]
Hey! In the current release, killfeeds do not work but there is a [working implementation](https://github.com/ampreeT/SourceCoop/pull/130) that will make it in the next release. We plan on dropping the new release early next month!

**Comment by Alienmario** [comment]
To get latest development build, go to actions tab on this repository, select latest run in 'master' branch, then you'll find updated archives. Use with discretion.

The project you mentioned is not affiliated, but it's worth a try asking about on discord.

**Comment by gysiguy** [comment]
Awesome! The killfeed works now!! Thank you for your help.

Which discord server should I try to ask on?
