### ISSUE TITLE
This coop teleport in bm_c4a1a1 is glitched

### ISSUE THREAD

**Issue by shodanx2** [ampreeT/SourceCoop#193]
![image](https://github.com/user-attachments/assets/c49bfa51-764c-483f-8e8e-ffd5e42c8ce0)

My friend went through and I couldn't , it just didn't pass

**Comment by shodanx2** [comment]
sorry it is the map before that

**Comment by Alienmario** [comment]
This is part of the map and one way only

**Comment by shodanx2** [comment]
Thanks ! I must have gotten it wrong !
I was following my friend, he made it to the exit, I searched everywhere and couldn't find it. I thought this teleport was the way out but malfunctioning !
The exit must have been somewhere else !
