### ISSUE TITLE
Minor visual issue with gluon gun appears "under" machinery object

### ISSUE THREAD

**Issue by shodanx2** [ampreeT/SourceCoop#197]
Another observation during play

The beam of the gluon gun is sometimes "under" other effects

Also happened with shooting near portal

![bms_5J2M5dz285](https://github.com/user-attachments/assets/c67a4624-fb68-4b86-b97b-4ffabf0effe2)

**Comment by shodanx2** [comment]
that game was so pretty

**Comment by Alienmario** [comment]
This should be targeted to CC, we don't touch anything regarding clientside rendering.
