### ISSUE TITLE
Singleplayer Crossbow/357 Ironsights

### ISSUE THREAD

**Issue by ampreeT** [ampreeT/SourceCoop#20]
convar exists to smooth zoom, investigate forcing clientside weapon animation for ironsights with SendWeaponAnim vtable func

**Comment by Alienmario** [comment]
These weapons have following sendprops, a quick toggle test showed it can work:

  Member: m_bIronSights (offset 1428) (type integer) (bits 1) (Unsigned)
  Member: m_bIronSightsScopePostprocess (offset 1429) (type integer) (bits 1) (Unsigned)
  Table: m_IronsightTransitionTimer (offset 1432) (type DT_CountdownTimer)
   Member: m_duration (offset 4) (type float) (bits 0) (NoScale)
   Member: m_timestamp (offset 8) (type float) (bits 0) (NoScale)
