### ISSUE TITLE
Crashes with latest development versions of MM and SM

### ISSUE THREAD

**Issue by hk135** [ampreeT/SourceCoop#34]
Hi There

So following the readme install process on a Linux dedicated I ended up with a segfault related to dhooks I think, I found some servers in the server browser and used the same versions, what worked for me was:

Metamod 1.11.0-git1130-linux
SourceMod 1.11.0-git6562
Dhooks with detours dhooks-2.2.0-detours14a-sm110

I noticed a server claiming to be your test server and it wasn't running the latest dev versions either, just thinking it may be an idea to list the specific versions you are using to test with incase others come across these issues.

Thanks

**Comment by Alienmario** [comment]
Hi,
It seems sourcemod builds 6609 and up crash on startup when our plugin is loaded, also with some other plugins. 
I will update the readme with recommended versions.
