### ISSUE TITLE
Any Plans for HL2?

### ISSUE THREAD

**Issue by hk135** [ampreeT/SourceCoop#35]
Hi There

Love the mod! Any plans to eventually do this with HL2?

Thanks

**Comment by Alienmario** [comment]
That would be a no from me, for HL2 you already have Synergy, Obisidan Conflict, or HL2DM coop servers to enjoy, which are way more established.

**Comment by hk135** [comment]
Fair enough, was unaware of the other mods hence the question. Thanks for getting back to me.
