### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by Azocki** [ampreeT/SourceCoop#38]
Hello, i tried installing it but i have no clue at all how to install it i followed what my hosting provider said but it doesnt work, they told me to contact here to make a issue report that it doesnt really support Linux or something..

giving me steam errors or some weird stuff in console
can anyone make a documentation or installation tutorial?

Thanks

**Comment by Alienmario** [comment]
It supports linux (although it has occasional random crashes and the game is generally more buggy on it).

Post your console log here.
Did you try running just a dm server? The linux server has a issue where you need to copy or link a file.

**Comment by Azocki** [comment]
what server hosting do you recommend me.. idk know any others... (it must accept btc)

well i can run it locally but how can i run it on a Windows VPS/RDP
how do i get a dedicated server running.

**Comment by Alienmario** [comment]
I use g-portal.com to host the development server. It's an EU game host, but doesn't accept btc afaik.

As for managing a server yourself you either use SteamCMD or a managing tool built around it.
See https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by Azocki** [comment]
same..

**Comment by Azocki** [comment]
yeah idk they told me linux shit but it isnt working they said its the "this addon" issue

**Comment by Azocki** [comment]
idfk anymore wanted to play together with friends but seems like i have todo some fucking ass installation wow....

**Comment by Azocki** [comment]
If you could show me how to isntall it on gportal would be awesome

**Comment by Alienmario** [comment]
First you should open a ticket and give them this information, preferably with a clean server install, so it can be verified it worked.
If your server works on a clean install, you can ignore this. I'll try to get a more detailed guide for the plugin out sooner.

> Either copy or link "Black Mesa Dedicated Server\bin\dedicated_srv.so" to "Black Mesa Dedicated Server\bin\dedicated.so"

**Comment by Azocki** [comment]
its clean if you want i can give you access to the ftp i can pay you in BTC..

**Comment by Alienmario** [comment]
I have rather finished the step by step guide. Everything you need to know to get it running is either in my comments above or the guide.
https://steamcommunity.com/sharedfiles/filedetails/?id=2200247356

If you still have questions you can add a comment on the guide. Thanks.

**Comment by Azocki** [comment]
Amazing guide, bro love it thanks alot
