### ISSUE TITLE
Stuck at "Parsing game info", bm_c2a4e (tripmine room)

### ISSUE THREAD

**Issue by MXYLR** [ampreeT/SourceCoop#40]
![V4CKOD1DCN2RNC57UIN1DT](https://user-images.githubusercontent.com/37480216/98121564-6cb65000-1eea-11eb-9433-f0e2e1b2ee26.png)
after finished bm_c2a4d, we reconnect and wait server changing level, but stuck here

**Comment by Alienmario** [comment]
Your server probably crashed. Random crashes can still happen.

**Comment by MXYLR** [comment]
> Your server probably crashed. Random crashes can still happen.

I reboot my server but I still get stuck here

**Comment by MXYLR** [comment]
nvm Im dump, just type `sm_map` to change the crash map then `kill` the pid and use `nohup` to lauch server.
