### ISSUE TITLE
Some issues that I want to share

### ISSUE THREAD

**Issue by tomaszbanach12** [ampreeT/SourceCoop#41]
Hello.
First of all, let me thank You for that modification.
I always wanted to play BMS on coop with my friends.
Couple days ago I saw your project on Steam workshop,
I installed addons on dedicated server like you mention in readme and... It works!

Btw I found some bugs that I wanted to share with you.
1. Server crashes, everytime I switch level to: [bm_c1a0b].
2. When I clicked mouse right click with .357 revolver and then pressed scroll button, animation get stuck at ironsight mode.
3. Somewhere in the start of the level [bm_c2a1a], my friend was teleported at the end of the map.

I was searching for some of that issues here, but i cannot find, so i wrote.

Greetings,
T.

**Comment by Alienmario** [comment]
Hi.
I can't reproduce your issues 1 and 2.
2. For ironsight mode, you mean just the screen zoom in, right? My game doesn't have iron sights in MP.
3. Are you sure that was not a checkpoint spawn after your friend died? A screenshot would be useful.

Please check that you have the latest version, no mods etc.

**Comment by tomaszbanach12** [comment]
1. Have you tried to connect to the server when this map was runinng?
2. Yes, but now i see that this bug comes directly from Black Mesa, because on normal multiplayer mode i have the same issue.
3. Yesterday we played this map again and everything was okey. 

I don't have any other mods, and I have latest version.

**Comment by Alienmario** [comment]
1. Yes, still no crash whatsoever. Does this happen with just 1 player? Does it depend from which map you switch? What's your server OS?

**Comment by Alienmario** [comment]
Hi, are you still having issues?

**Comment by tomaszbanach12** [comment]
Yes. I still have that issue mentioned in point 1. Server goes down when somebody join while levels [bm_c1a0b] and also [bm_c2a5a] are running on the server. What I see is that those leveles are first maps from chapters (Unforseen Consequences and Surface Tension), but idk is it an important remark.

**Comment by Alienmario** [comment]
Can you do a full reinstall? Or at least verify server files + reinstall sourcecoop?

Alternatively, can you try using the versions in this guide rather than the readme ? https://steamcommunity.com/sharedfiles/filedetails/?id=2200247356
