### ISSUE TITLE
Inventory on level change

### ISSUE THREAD

**Issue by pkurras** [ampreeT/SourceCoop#44]
**Steps to reproduce**
1. Get a gun.
2. Enter the next level change trigger.

**Actual Result**
After the level change, notice that you have different weapons/ammunition than before.
Sometimes you spawn with your crowbar only.

**Expected Result**
Weapons should carry over with the same ammunition count, you've had before the level change.

**Comment by Alienmario** [comment]
Hi, I think this won't be implemented, unless someone else wants to take the time to do so. IMO, it would be difficult to balance it, one issue is players joining mid game.
