### ISSUE TITLE
Killfeed and Killsound Convars

### ISSUE THREAD

**Issue by Rock48** [ampreeT/SourceCoop#45]
There should be convars for server operators to decide whether to have the killfeed and killsound cookies be on or off by default as well as a convar to choose the sound used in the killsounds plugin (potentially convars for choosing sounds used for level change timer etc too)

I'll work on this later tonight probably

**Comment by Alienmario** [comment]
I've added convars for the defaults. If you still want to implement configurable sounds feel free to create another issue.
