### ISSUE TITLE
Player character glowing in dark compared to NPCs?

### ISSUE THREAD

**Issue by 4nthonyy** [ampreeT/SourceCoop#52]
I noticed this when I found my ragdoll , the body had much stronger color that it was kinda glowing. Not sure if this is itentional?

**Comment by 4nthonyy** [comment]
Tested it a bit more, specifically guards model shirt is glowing and some parts on HEV suit model. I will upload pictures later.

**Comment by Alienmario** [comment]
This is most likely unrelated to the mod.

**Comment by 4nthonyy** [comment]
Could be, but to get the better picture:  

https://steamuserimages-a.akamaihd.net/ugc/1693899082406305567/3F0C2BD5DEF6ACD846FEA406260C0E0B7DEFD78F/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by 4nthonyy** [comment]
Uh , this seems to be the issue with the game not mod. Just tried it in multiplayer. Same thing there.
Up to devs to fix I guess.
