### ISSUE TITLE
Remove tied player score count at the top

### ISSUE THREAD

**Issue by LukeShortCloud** [ampreeT/SourceCoop#60]
On any dedicated server I start, the text "TIED | 0 - 0" is displayed at the top of the screen while in-game. This never changes as I assume this is for a typical Death Match multiplayer game. It takes me and my friends out of the universe when playing the campaign. Is there any way to disable this?

I am not sure if this is a Source, Black Mesa, and/or SourceCoop issue. These are two commands I tried client-side which appear to actually be unrelated: `-score` and `-showscore`.

**Comment by Alienmario** [comment]
This is because our mod runs in the multiplayer version of the game.
It's one of the things we haven't figured out how to hide yet.
