### ISSUE TITLE
Map bm_c1a3a

### ISSUE THREAD

**Issue by RocKs-Painkiller** [ampreeT/SourceCoop#61]
stuck in the shaft can not move.

Latest version of Sourcecoop
Linux Dedicated Server

**Comment by Alienmario** [comment]
Can you provide more detail or a screenshot?

**Comment by RocKs-Painkiller** [comment]
This error has appeared once before.

**Comment by Alienmario** [comment]
I'll close this for now since there isn't enough information and it hasn't happened while playtesting.

**Comment by RocKs-Painkiller** [comment]
We can test it at my place if you like.
It happens every time.

**Comment by Alienmario** [comment]
Let's do it.

**Comment by RocKs-Painkiller** [comment]
178.63.54.240:28220
