### ISSUE TITLE
Major server performance drop by multiple npc_gargantua

### ISSUE THREAD

**Issue by Balimbanana** [ampreeT/SourceCoop#63]
More particularly on bm_c4a3a1 which has the garg chase. Each gargantua has 57 `phys_bone_followers` which is causing the major amount of lag server-side. You can't quite just remove them all because that is their entire hit box, you will only collide with their feet without any bone followers.
I have found that keeping around 6 - 10 using `m_physicsBone` indexes 0 - 5 or 0 - 9 has *most* of a hit box so clients rpg and other weapons will actually hit something, even though they are usually invulnerable.
If there is only one garg active, having all 57 bones is probably fine.

**Comment by Alienmario** [comment]
Thanks for the report. I haven't had the time to investigate the reason of the garg lag, this helps.

**Comment by Alienmario** [comment]
I was able to work around it by by deleting all followers and setting the Garg's solid type to SOLID_BBOX. This provided an acceptable bounding box around the center body, excluding the arms.

Now I'm looking for an efficient way to find the followers in order to kill them.

**Comment by Balimbanana** [comment]
The way I tested it was by:
```
int iOwner = -1;
int iEntity = -1;
while((iEntity = FindEntityByClassname(iEntity, "phys_bone_follower")) != INVALID_ENT_REFERENCE)
{
	if (IsValidEntity(iEntity))
	{
		if (HasEntProp(iEntity, Prop_Data, "m_hOwnerEntity"))
		{
			iOwner = GetEntPropEnt(iEntity, Prop_Data, "m_hOwnerEntity");
			if (IsValidEntity(iOwner))
			{
				GetEntityClassname(iOwner, szClassname, sizeof(szClassname));
				if (StrEqual(szClassname, "npc_gargantua", false))
				{
					// Either remove or get the m_physicsBone
				}
			}
		}
	}
}

**Comment by Alienmario** [comment]
Fixed
