### ISSUE TITLE
Auto Difficult change.

### ISSUE THREAD

**Issue by Enrory** [ampreeT/SourceCoop#66]
Hello 

i added this 2 commands to my server.cfg file. 

sourcecoop_difficulty_auto_min 30
sourcecoop_difficulty_auto_max 100

but nothing changed by mapchange. start with 1 player with 2 i think. 
pls help

**Comment by Alienmario** [comment]
Add sourcecoop_difficulty_auto 0

**Comment by Enrory** [comment]
hmmm i think its default 0 
i will try

**Comment by Enrory** [comment]
thanks it works now :) 

btw good job for this plugin 👍
