### ISSUE TITLE
Potential to improve the plugin? 

### ISSUE THREAD

**Issue by tmob03** [ampreeT/SourceCoop#72]
Sorry if this isn't the place to put this, idk where else.

I was looking through black  mesas entities today, and found these.  
![image](https://user-images.githubusercontent.com/33987871/158302076-960da2d8-c46f-4281-ae09-1031ed90bce7.png)

Potentially creating them and finding out which inputs affect them could make coop better or fix the crossbow? 

None of them are in the fgd, so it'd be a lot of trial and error.

**Comment by Alienmario** [comment]
We already use Sourcemod's way of peeking through the entities, but thank you anyways.
