### ISSUE TITLE
SourceCoop possibly not loading

### ISSUE THREAD

**Issue by AdamGaffney96** [ampreeT/SourceCoop#73]
Me and my friend gave the mod a go with me hosting the server for Black Mesa a few nights back, and it was really cool! However we were experiencing the crash on stage one of Unforseen Consequences and and issue where when dying once, the HUD disappeared and you couldn't take damage or do damage to anything else, however this isn't the issues I wanted to raise. I found some old issues regarding using newer versions of SourceMod etc being the possible issue. #58 

As a result of this I cleared my dedicated server install and decided to reinstall everything with the exact recommended versions. However now for some reason when running the same extraction process as before (as far as I can remember anyway) I just get loaded in as a regular MP scientist and none of the actual opening sequence plays. Plus I no longer have any sort of voting UI. Just wondering if perhaps I'm missing something with the install or if maybe there's a problem with the mod itself on these versions. I can provide any necessary logs to help with the issue.

All other info listed below:
```
SourceMod Version: 1.11.0 6645
SourceCo-Op Version: 1.0.4
DHooks Version: 2.2.0 SM110
MMSource Version: 1.11.0 1143
```
Server.cfg - Note that when the server loads I get "Unknown command" prompts in the server CLI for the SourceCoop options

```
mp_timelimit 0
mp_fraglimit 0
mp_teamplay 0
mp_forcerespawn 1
maxplayers 2
map bm_c0a0a
sourcecoop_respawntime 2.0
sourcecoop_team scientist
sourcecoop_start_wait_period 0
sourcecoop_disable_teamselect 1
```
The unknown commands
```
Unknown command "sourcecoop_respawntime"
Unknown command "sourcecoop_team"
Unknown command "sourcecoop_start_wait_period"
Unknown command "sourcecoop_disable_teamselect"
Unknown command "gb_flashlight_PosX"
Unknown command "gb_flashlight_PosY"
Unknown command "gb_flashlight_PosZ"
Unknown command "gb_flashlight_Intensity"
Unknown command "gb_flashlight_Col"
Unknown command "gb_flashlight_Range"
Unknown command "gb_flashlight_phi"
Unknown command "gb_flashlight_oldfalloff_quad"
Unknown command "gb_flashlight_oldfalloff_linear"
Unknown command "sk_zombie_one_slash_left_viewpunch"
Unknown command "sk_zombie_one_slash_right_viewpunch"
Unknown command "sk_zombie_both_slash_viewpunch"
Unknown command "cl_xort_light_col_R"
Unknown command "cl_xort_light_col_G"
Unknown command "cl_xort_light_col_B"
Unknown command "cl_xort_light_intensity"
Unknown command "cl_xort_light_range"
Unknown command "cl_xort_light_ttl_Zap"
Unknown command "cl_xort_light_ttl_dispel"
Unknown command "cl_envportal_light_col_R"
Unknown command "cl_envportal_light_col_G"
Unknown command "cl_envportal_light_col_B"
Unknown command "sk_apache_fire_cone_sta"
Unknown command "mat_bloom_nextgen"
Unknown command "cl_gargflame_spotL_col_R"
Unknown command "cl_gargflame_spotL_col_G"
Unknown command "cl_gargflame_spotL_col_B"
Unknown command "cl_gargflame_spotL_intensity"
Unknown command "cl_gargflame_spotL_range"
Unknown command "cl_gargflame_spotL_outer_angle"
Unknown command "cl_gargflame_spotL_inner_angle"
Unknown command "cl_gargflame_spotL_offset"
Unknown command "cl_gargflame_pointL_col_R"
Unknown command "cl_gargflame_pointL_col_G"
Unknown command "cl_gargflame_pointL_col_B"
Unknown command "cl_gargflame_pointL_intensity"
Unknown command "cl_gargflame_pointL_range"
Unknown command "cl_gargflame_pointL_offset"
Unknown command "cl_garg_eyeL_light_on"
Unknown command "cl_garg_eyeL_light_col_R"
Unknown command "cl_garg_eyeL_light_col_G"
Unknown command "cl_garg_eyeL_light_col_B"
Unknown command "cl_garg_eyeL_light_intensity"
Unknown command "cl_garg_eyeL_light_range"
Unknown command "cl_suitcharg_light_on"
Unknown command "cl_suitcharg_light_col_R"
Unknown command "cl_suitcharg_light_col_G"
Unknown command "cl_suitcharg_light_col_B"
Unknown command "cl_suitcharg_light_intensity"
Unknown command "cl_suitcharg_light_range"
Unknown command "cl_suitcharg_light_offset"
Unknown command "cl_hpcharg_light_on"
Unknown command "cl_hpcharg_light_col_R"
Unknown command "cl_hpcharg_light_col_G"
Unknown command "cl_hpcharg_light_col_B"
Unknown command "cl_hpcharg_light_intensity"
Unknown command "cl_hpcharg_light_range"
Unknown command "cl_suitcharg_light_offset"
```
srcds.bat - I run this via a button press on my Streamdeck however I get the same issues when running it by directly opening the file. This was how I launched the server before when it was working.
```
@echo off
cls
echo Protecting srcds from crashes...
echo If you want to close srcds and this script, close the srcds window and type Y depending on your language followed by Enter.
title srcds.com Watchdog
:srcds
echo (%time%) srcds started.
start /wait srcds.exe /high -console -game bms -secure -port 27016 +clientport 27017 +exec server.cfg
echo (%time%) WARNING: srcds closed or crashed, restarting.
goto srcds
```
Also this is my output when running sm plugins list. I'm pretty sure the sourcecoop line showed up previously when it did work.
```
  01 "Admin File Reader" (1.11.0.6645) by AlliedModders LLC
  02 "Admin Help" (1.11.0.6645) by AlliedModders LLC
  03 "Admin Menu" (1.11.0.6645) by AlliedModders LLC
  04 "Anti-Flood" (1.11.0.6645) by AlliedModders LLC
  05 "Basic Ban Commands" (1.11.0.6645) by AlliedModders LLC
  06 "Basic Chat" (1.11.0.6645) by AlliedModders LLC
  07 "Basic Comm Control" (1.11.0.6645) by AlliedModders LLC
  08 "Basic Commands" (1.11.0.6645) by AlliedModders LLC
  09 "Basic Info Triggers" (1.11.0.6645) by AlliedModders LLC
  10 "Basic Votes" (1.11.0.6645) by AlliedModders LLC
  11 "Client Preferences" (1.11.0.6645) by AlliedModders LLC
  12 "Fun Commands" (1.11.0.6645) by AlliedModders LLC
  13 "Fun Votes" (1.11.0.6645) by AlliedModders LLC
  14 Disabled: "Nextmap" (1.11.0.6645) by AlliedModders LLC
  15 "Player Commands" (1.11.0.6645) by AlliedModders LLC
  16 "Reserved Slots" (1.11.0.6645) by AlliedModders LLC
  17 "Sound Commands" (1.11.0.6645) by AlliedModders LLC
```
And finally here is the structure of my bms folder just in case something is wrong there. I have tried the SourceCoop stuff in its own folder and just in the main bms folder and neither works, hence why I feel like I'm missing something I did before. There are a ton of files in each folder of course so I've just shown the folder structure for ease.
```
Black Mesa Dedicated Server/bms
└───addons
│       └───metamod
│       └───sourcemod
└───bin
└───cfg
│       └───sourcemod
└───configs
│       └───sourcecoop
└───data
│       └───srccoop
└───downloadlists
└───gamecontent_bms
│       └───models
│       │       └───props_xen
└───gamedata
└───maps
│       └───graphs
│       └───soundcache
└───media
└───scripting
│       └───include
│       │       └───srccoop
└───user_custom
│       └───88
```
Let me know if I need to provide anything else, thanks.

**Comment by Alienmario** [comment]
The instructions here are for an unreleased version. Following the steam guide should work.
I can see your versions are correct but not your paths. Perhaps you installed SourceCoop outside of SourceMod?

**Comment by AdamGaffney96** [comment]
Thanks for the response. That's what's so confusing to me is that I followed the Steam Guide the first time (albeit using sourcemod 6863 hence what probably caused the Unforseen Consequences crash) and it worked perfectly. From what I understand I have followed the same steps again and this time nothing seems to be working. 

Am I correct in saying that the SourceCoop folders (i.e. configs, data etc) should just be extracted directly into "Black Mesa Dedicated Server/bms"? This is the only thing I can't quite remember what I did the first time, and my suspicion is this is causing the issue.

**Comment by Alienmario** [comment]
All the zips are packaged so that their root starts at "bms".

**Comment by AdamGaffney96** [comment]
Ah hold on, I realise what I've done. When I redownloaded the SourceCoop package, I got the Source Code zip rather than the basic "sourcecoop-1.0.4.zip" in the file list. Apologies for wasting your time, that'll be why my structure was all wrong. Thanks for your patience.
