### ISSUE TITLE
Empty handed players T-Pose

### ISSUE THREAD

**Issue by Alienmario** [ampreeT/SourceCoop#76]
To Reproduce: remove crowbar from bm_c1a0a.edt and change to it, go to thirdperson.

Tested various server side fixes but none worked, all animations and poses appear to be clientsided.

**Comment by Balimbanana** [comment]
This might be possible to kind of work around. There is an input to CBaseCombatWeapon of HideWeapon which hides both the world model, and the viewmodel. Then we would run PreventWeaponFiring on it and the player will stay in whichever animation that weapon had.

Running through the weapons, the `weapon_satchel` *appears* to be the best candidate for what looks ok while appearing to hold no weapon.

**Comment by Alienmario** [comment]
Ideally I'd like to avoid workarounds that complicate extensibility and require workarounds in other places themselves (e.g for item persistence).

My next best thought was to look into what can be done by modifying player models themselves.

**Comment by MyGamepedia** [comment]
Just want to note that we have `_noweapon` animations in all player models.
