### ISSUE TITLE
map error bm_c2a2a

### ISSUE THREAD

**Issue by RocKs-Painkiller** [ampreeT/SourceCoop#81]
Coordinates on the image

One: bm_c2a2a
https://www.rocks-clan.de/downloads/bms%20error.png

Two: bm_c2a2c
https://www.rocks-clan.de/downloads/bms%20error%201.png

Three: bm_c2a2c
https://www.rocks-clan.de/downloads/bms%20error%202.png

Four: c2a3a
https://www.rocks-clan.de/downloads/bms%20error%203.png

Five: bm_c2a3b
https://www.rocks-clan.de/downloads/bms%20error%204.png

Six: bm_c2a3c
https://www.rocks-clan.de/downloads/bms%20error%205.png

Seven: bm_c2a4a
https://www.rocks-clan.de/downloads/bms%20error%205.png

Eight: bm_c2a4b
https://www.rocks-clan.de/downloads/bms%20error%207.png

Nine:  bm_c2a5b
https://www.rocks-clan.de/downloads/bms%20error%209.png

Nine: bm_c2a4h
https://www.rocks-clan.de/downloads/bms%20error%208.png

Ten: bm_c2a5d
https://www.rocks-clan.de/downloads/bms%20error%2010.png
https://www.rocks-clan.de/downloads/bms%20error%2010.1.png

**Comment by Alienmario** [comment]
Not related to the mod.

**Comment by RocKs-Painkiller** [comment]
Strange, I tested it in single player and everything was ok.

Then I played the mod and there these errors occurred.

**Comment by Alienmario** [comment]
No-one else reported this.

**Comment by RocKs-Painkiller** [comment]
Then I am the first

**Comment by Balimbanana** [comment]
It is quite odd that it would only occur during multiplayer. Those appear to be shader issues drawing terrain. Another potential is if you have any CVars set when you search in console:
`find wireframe`

Have you tried Verify integrity of game files? Maybe there is something missing somehow. 
Also, what graphics card are you using?
