### ISSUE TITLE
Instruction for running dedicated server with black mesa (and make pterodactyl egg of it)

### ISSUE THREAD

**Issue by shodanx2** [ampreeT/SourceCoop#86]
Hi,

I've played through this with a friend a couple months ago and it was really great.

Now I would like to do it again, with 3 players and instead of running on my computer with the client, I want to create a permanently running black mesa dedicated server

Could you provide some instructions on how to do that ?

**Comment by shodanx2** [comment]
Thanks, I will give that a try
Pterodactyl was a little bit too much for me, although it worked. It was a bit too automatic. 
When it worked it was great,  when it didn't it was very difficult to repair

Linuxgsm seems a nice in between level of complexity, automation and repairability

**Comment by Alienmario** [comment]
If you want lighter version of pterodactyl there's also pufferpanel. It just supports source dedicated servers, though not specifically BM. (Just install the dependencies listed in linuxgsm page beforehand or you may have weird issues as I once did).

**Comment by shodanx2** [comment]
Thanks looking forward to giving this another try at my next lan party :)
