### ISSUE TITLE
Run half-life 2 vr with sourcecoop ?

### ISSUE THREAD

**Issue by shodanx2** [ampreeT/SourceCoop#89]
Is this possible ?

**Comment by Alienmario** [comment]
Not sure if possible or not, however not worth the resources without large enough demand. Multiplayer component needs to be present in the game for the mod to work. If you can use VR in HL2:DM then that would be more probable.

**Comment by shodanx2** [comment]
I am curious in light of these news

https://old.reddit.com/r/Games/comments/12e3xi2/black_mesa_vr_mod_public_beta_release_trailer/
https://mixed-news.com/en/half-life-2-episode-two-black-mesa-vr-mod-launch/

and these mods

https://www.nexusmods.com/halflife2episode2/mods/4
https://store.steampowered.com/app/658920/HalfLife_2_VR_Mod/
https://store.steampowered.com/app/2177750/HalfLife_2_VR_Mod__Episode_One/
https://store.steampowered.com/app/2177760/HalfLife_2_VR_Mod__Episode_Two/

I was curious if it would be possible to combine with SourceCoop

(Also, it is been a long time, I don't remember, is SourceCoop the same thing as "synergy" ?)
https://store.steampowered.com/app/17520/Synergy/
