### ISSUE TITLE
npc sleepstates do not work

### ISSUE THREAD

**Issue by ampreeT** [ampreeT/SourceCoop#9]
witnessed in the office complex levels where in the freezer, the scientists are already dead due to the zombies sleepstates not correctly being set

**Comment by Alienmario** [comment]
likely caused by this function
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.cpp#L3353
