### ISSUE TITLE
Map stuck bm_c4a3d

### ISSUE THREAD

**Issue by Alienmario** [ampreeT/SourceCoop#98]
At the start, bottom of the elevator, where a controller is supposed to throw something at the glass and break it, the map often gets stuck.

**Comment by MCone4SV** [comment]
Found why is it stuck. The player may get stuck above the glass in the vent and the controller will throw the barrel in wrong direction. Got that on video https://www.youtube.com/watch?v=523ZudDZCl0
After using noclip and killing controller the elevator goes fine

**Comment by Alienmario** [comment]
https://github.com/ampreeT/SourceCoop/commit/e82e58d35070b26255bd8c089bef08c1b51e96cc
